/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui.bearbeiten;

import sportverein.gui.datenAusgabe.ListModels;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import sportverein.gui.Interfaces.Updatable;
import sportverein.gui.dialoge.SchiedsrichterBearbeitenDialog;
import sportverein.gui.dialoge.SindSieSicherDialog;
import sportverein.gui.dialoge.SportartenBearbeitenDialog;
import sportverein.gui.dialoge.SportlerBearbeitenDialog;
import sportverein.handler.Help;
import sportverein.models.Mitglied;
import sportverein.models.Person;
import sportverein.models.Sportart;
import sportverein.models.Sportler;
import sportverein.handler.Verwaltung;
import sportverein.models.Schiedsrichter;
import sportverein.models.Vorstand;

/**
 *
 * @author steffen
 */
public class SchiedsrichterBearbeitenPanel extends javax.swing.JPanel implements Updatable{

    /**
     * Creates new form Sportler
     */
    public SchiedsrichterBearbeitenPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_sportler = new javax.swing.JLabel();
        scrollPane_sportarten = new javax.swing.JScrollPane();
        list_schiedsrichter = new javax.swing.JList();
        button_loeschen = new javax.swing.JButton();
        lbl_anzahl_schiedsrichter = new javax.swing.JLabel();
        button_bearbeiten1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sportler.setText("Schiedsrichter");
        add(lbl_sportler, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        list_schiedsrichter.setModel(ListModels.getSchiedsrichter());
        list_schiedsrichter.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPane_sportarten.setViewportView(list_schiedsrichter);

        add(scrollPane_sportarten, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 270));

        button_loeschen.setText("Löschen");
        button_loeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loeschenActionPerformed(evt);
            }
        });
        add(button_loeschen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, -1));

        lbl_anzahl_schiedsrichter.setText(String.valueOf(Verwaltung.getInstance().getSchiedsrichter().size()));
        add(lbl_anzahl_schiedsrichter, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        button_bearbeiten1.setText("Bearbeiten");
        button_bearbeiten1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bearbeiten1ActionPerformed(evt);
            }
        });
        add(button_bearbeiten1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void button_loeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loeschenActionPerformed
        // TODO add your handling code here:
        try {
            String schiesdrichterInfo = (String )list_schiedsrichter.getSelectedValue();
             int nr = Help.getMitgliedNrVonInfoString(schiesdrichterInfo);
            Schiedsrichter schi = Verwaltung.getInstance().findSchiedsrichter(nr);
            if (Verwaltung.getInstance().getSchiedsrichter().contains(schi)){
              SindSieSicherDialog dialog = new SindSieSicherDialog(new javax.swing.JFrame(), true, "Möchten Sie dieses Mitglied \n" + schi.getInfoString() + "\n wirklich löschen?");
              if (dialog.showDialog()) {
                  Verwaltung.getInstance().getSchiedsrichter().remove(schi);
                  this.updateViews();
              }  
            }
        } catch (NullPointerException e) {
            System.out.println("Zeige Dialog");
           JOptionPane.showMessageDialog(null, "Bitte wählen sie ein Sportler aus.");
        }
    }//GEN-LAST:event_button_loeschenActionPerformed

    private void button_bearbeiten1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bearbeiten1ActionPerformed
        try {
            String schiedsrichterInfo = (String )list_schiedsrichter.getSelectedValue();
            int nr = Help.getMitgliedNrVonInfoString(schiedsrichterInfo);
            System.out.println("Schiedsrichter Nummer "+nr);
            Schiedsrichter schi = Verwaltung.getInstance().findSchiedsrichter(nr);
            System.out.println(schi.getName());
            SchiedsrichterBearbeitenDialog dialog = new SchiedsrichterBearbeitenDialog(new javax.swing.JFrame(), true, schi);
            if (dialog.showDialog()){
              this.updateViews();
            }
        } catch (NullPointerException e) {
            System.out.println("Zeige Dialog");
           JOptionPane.showMessageDialog(null, "Bitte wählen sie ein Sportler aus.");
        }
              
       // dialog.setVisible(true);
    }//GEN-LAST:event_button_bearbeiten1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_bearbeiten1;
    private javax.swing.JButton button_loeschen;
    private javax.swing.JLabel lbl_anzahl_schiedsrichter;
    private javax.swing.JLabel lbl_sportler;
    private javax.swing.JList list_schiedsrichter;
    private javax.swing.JScrollPane scrollPane_sportarten;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateViews() {
        list_schiedsrichter.setModel(ListModels.getSchiedsrichter());
        lbl_anzahl_schiedsrichter.setText(String.valueOf(Verwaltung.getInstance().getSchiedsrichter().size()));
        
    }
}
