/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui.bearbeiten;

import javax.swing.JOptionPane;
import sportverein.gui.Interfaces.Updatable;
import sportverein.gui.datenAusgabe.ListModels;
import sportverein.gui.dialoge.SindSieSicherDialog;
import sportverein.handler.Verwaltung;
import sportverein.models.Spiel;

/**
 *
 * @author Hans
 */
public class SpielBearbeitenPanel extends javax.swing.JPanel  implements Updatable{

    /**
     * Creates new form SpielBearbeitenPanel
     */
    public SpielBearbeitenPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_spiel = new javax.swing.JLabel();
        lbl_anzahl_spiel = new javax.swing.JLabel();
        scrollPane_sportarten = new javax.swing.JScrollPane();
        list_Spiele = new javax.swing.JList();
        button_bearbeiten1 = new javax.swing.JButton();
        button_loeschen = new javax.swing.JButton();

        lbl_spiel.setText("Spiele");

        lbl_anzahl_spiel.setText(String.valueOf(Verwaltung.getInstance().getMannschaft().size()));

        list_Spiele.setModel(ListModels.getSpiel());
        list_Spiele.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPane_sportarten.setViewportView(list_Spiele);

        button_bearbeiten1.setText("Bearbeiten");
        button_bearbeiten1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bearbeiten1ActionPerformed(evt);
            }
        });

        button_loeschen.setText("Löschen");
        button_loeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loeschenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane_sportarten, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_bearbeiten1)
                            .addComponent(button_loeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_spiel)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_anzahl_spiel)))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_spiel)
                    .addComponent(lbl_anzahl_spiel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_bearbeiten1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_loeschen))
                    .addComponent(scrollPane_sportarten, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_bearbeiten1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bearbeiten1ActionPerformed


        // dialog.setVisible(true);
    }//GEN-LAST:event_button_bearbeiten1ActionPerformed

    private void button_loeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loeschenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_button_loeschenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_bearbeiten1;
    private javax.swing.JButton button_loeschen;
    private javax.swing.JLabel lbl_anzahl_spiel;
    private javax.swing.JLabel lbl_spiel;
    private javax.swing.JList list_Spiele;
    private javax.swing.JScrollPane scrollPane_sportarten;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateViews() {
        list_Spiele.setModel(ListModels.getSpiel());
        lbl_anzahl_spiel.setText(String.valueOf(Verwaltung.getInstance().getSpiel().size()));
    }
}
