/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui;

import ausgabe.DateiAusgabe;
import eingabe.DateiEingabe;
import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SpringLayout;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import schnittstellen.IAusgabe;
import schnittstellen.IEingabe;
import sportverein.gui.Interfaces.Updatable;
import sportverein.handler.Help;
import sportverein.models.Mitglied;
import sportverein.handler.Verwaltung;

/**
 *
 * @author steffen
 */
public class Gui extends javax.swing.JFrame implements Updatable{
    
    /**
     * Creates new form NewJFrame
     */
    public Gui() {

        initDatenbestand();
        initComponents();
        System.out.println(Verwaltung.getInstance().getAnzahlMitglieder());
        System.out.println(Verwaltung.getInstance().getSportler().size());
    }
    private void initDatenbestand() {
        IEingabe eingabe = new DateiEingabe();
        Verwaltung.getInstance().setVerwaltung(
                ((DateiEingabe)eingabe).getSportler(), 
                ((DateiEingabe)eingabe).getVorstand(), 
                ((DateiEingabe)eingabe).getSchiedsrichter(), 
                ((DateiEingabe)eingabe).getSportarten(), 
                ((DateiEingabe)eingabe).getTrainer(), 
                ((DateiEingabe)eingabe).getSpiele(), 
                ((DateiEingabe)eingabe).getMannschaften(), 
                "PseudoNutzer");
    }
    
    
   
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        neuesMitgliedAnlegen2 = new sportverein.gui.anlegen.AnlegenPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dashboard1 = new sportverein.gui.Dashboard();
        anlegenPanel = new sportverein.gui.anlegen.AnlegenPanel();
        bearbeitenPanel1 = new sportverein.gui.bearbeiten.BearbeitenPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuI_Laden = new javax.swing.JMenuItem();
        jMnuI_Speichern = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(Help.getScreenSize());

        jTabbedPane1.addTab("Dashboard", dashboard1);
        jTabbedPane1.addTab("Anlegen", anlegenPanel);
        jTabbedPane1.addTab("Bearbeiten", bearbeitenPanel1);

        jMenu1.setText("File");

        jMnuI_Laden.setText("Laden");
        jMnuI_Laden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuI_LadenActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuI_Laden);

        jMnuI_Speichern.setText("Speichern");
        jMnuI_Speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuI_SpeichernActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuI_Speichern);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuI_LadenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuI_LadenActionPerformed
        IEingabe eingabe = new DateiEingabe();
        eingabe.liesDaten();
        updateViews();
        
    }//GEN-LAST:event_jMnuI_LadenActionPerformed

    private void jMnuI_SpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuI_SpeichernActionPerformed
        Verwaltung verwaltung = Verwaltung.getInstance();
        IAusgabe ausgabe = new DateiAusgabe();
        ausgabe.schreibeDaten(verwaltung.getSportart(), verwaltung.getSchiedsrichter(), verwaltung.getSportler(), verwaltung.getVorstand(), verwaltung.getTrainer(), verwaltung.getSpiel(), verwaltung.getMannschaft());
    }//GEN-LAST:event_jMnuI_SpeichernActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void starteGui(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Gui gui = new Gui();
                    gui.setVisible(true);
                    
                    gui.jTabbedPane1.addChangeListener(new ChangeListener() {

                    @Override
                    public void stateChanged(ChangeEvent e) {
                       System.out.print("update Views");
                       gui.dashboard1.updateViews();
                       gui.bearbeitenPanel1.updateViews();
                       gui.anlegenPanel.updateViews();
                    }
                });
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sportverein.gui.anlegen.AnlegenPanel anlegenPanel;
    private sportverein.gui.bearbeiten.BearbeitenPanel bearbeitenPanel1;
    private sportverein.gui.Dashboard dashboard1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuI_Laden;
    private javax.swing.JMenuItem jMnuI_Speichern;
    private javax.swing.JTabbedPane jTabbedPane1;
    private sportverein.gui.anlegen.AnlegenPanel neuesMitgliedAnlegen2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateViews() {
       this.dashboard1.updateViews();
       this.bearbeitenPanel1.updateViews();
       this.anlegenPanel.updateViews();
    }
}
