/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui;

import eingabe.DateiEingabe;
import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SpringLayout;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import schnittstellen.IEingabe;
import sportverein.Help;
import sportverein.Mitglied;
import sportverein.Verwaltung;

/**
 *
 * @author steffen
 */
public class Gui extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame
     */
    public Gui() {

        initDatenbestand();
        initComponents();
        System.out.println(Verwaltung.getInstance().getAnzahlMitglieder());
        System.out.println(Verwaltung.getInstance().getSportler().size());
    }
    private void initDatenbestand() {
        IEingabe eingabe = new DateiEingabe();
        Verwaltung.getInstance().setVerwaltung(
                ((DateiEingabe)eingabe).getSportler(), 
                ((DateiEingabe)eingabe).getVorstand(), 
                ((DateiEingabe)eingabe).getSchiedsrichter(), 
                ((DateiEingabe)eingabe).getSportarten(), 
                ((DateiEingabe)eingabe).getTrainer(), 
                ((DateiEingabe)eingabe).getSpiele(), 
                ((DateiEingabe)eingabe).getMannschaften(), 
                "PseudoNutzer");
    }
    
    
   
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        neuesMitgliedAnlegen2 = new sportverein.gui.AnlegenPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dashboard1 = new sportverein.gui.Dashboard();
        anlegenPanel = new sportverein.gui.AnlegenPanel();
        bearbeitenPanel1 = new sportverein.gui.BearbeitenPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(Help.getScreenSize());

        jTabbedPane1.addTab("Dashboard", dashboard1);
        jTabbedPane1.addTab("Anlegen", anlegenPanel);
        jTabbedPane1.addTab("Bearbeiten", bearbeitenPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void starteGui(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Gui gui = new Gui();
                    gui.setVisible(true);
                    
                    gui.jTabbedPane1.addChangeListener(new ChangeListener() {

                    @Override
                    public void stateChanged(ChangeEvent e) {
                       System.out.print("update Labels");
                       gui.dashboard1.updateTexts();
                       
                    }
                });
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sportverein.gui.AnlegenPanel anlegenPanel;
    private sportverein.gui.BearbeitenPanel bearbeitenPanel1;
    private sportverein.gui.Dashboard dashboard1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private sportverein.gui.AnlegenPanel neuesMitgliedAnlegen2;
    // End of variables declaration//GEN-END:variables
}
