/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import sportverein.Help;
import sportverein.Mannschaft;
import sportverein.Mitglied;
import sportverein.Person;
import sportverein.Sportart;
import sportverein.Sportler;
import sportverein.Verwaltung;

/**
 *
 * @author steffen
 */
public class SpielAnlegenPanel extends javax.swing.JPanel {

    /**
     * Creates new form Sportler
     */
    public SpielAnlegenPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_allgemeineInfos = new javax.swing.JLabel();
        lbl_mannschaft1 = new javax.swing.JLabel();
        lbl_mannschaft2 = new javax.swing.JLabel();
        lbl_datum = new javax.swing.JLabel();
        lbl_day = new javax.swing.JLabel();
        comboBox_day = new javax.swing.JComboBox();
        lbl_month = new javax.swing.JLabel();
        comboBox_month = new javax.swing.JComboBox();
        lbl_year = new javax.swing.JLabel();
        comboBox_year = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        button_speichern = new javax.swing.JButton();
        combo_sportart = new javax.swing.JComboBox<>();
        combo_mannschaft1 = new javax.swing.JComboBox<>();
        combo_mannschaft2 = new javax.swing.JComboBox<>();
        lbl_sportart = new javax.swing.JLabel();
        btn_uebernehmen = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setText("Legen sie ein Spiel an");
        add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, 404, 44));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 56, 591, -1));

        lbl_allgemeineInfos.setText("Allgemeine Informationen");
        add(lbl_allgemeineInfos, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 74, -1, -1));

        lbl_mannschaft1.setText("Mannschaft 1");
        add(lbl_mannschaft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lbl_mannschaft2.setText("Mannschaft 2");
        add(lbl_mannschaft2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lbl_datum.setText("Datum");
        add(lbl_datum, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 236, -1, -1));

        lbl_day.setText("Tag");
        add(lbl_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 236, 85, -1));

        comboBox_day.setModel(ComboBoxModels.getTage());
        add(comboBox_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        lbl_month.setText("Monat");
        add(lbl_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 236, 85, -1));

        comboBox_month.setModel((ComboBoxModels.getMonate()));
        add(comboBox_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 270, -1, -1));

        lbl_year.setText("Jahr");
        add(lbl_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 236, 110, -1));

        comboBox_year.setModel(ComboBoxModels.getJahre());
        add(comboBox_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 270, 110, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 303, 591, 10));

        button_speichern.setText("Speichern");
        button_speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_speichernActionPerformed(evt);
            }
        });
        add(button_speichern, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        combo_sportart.setModel(ComboBoxModels.getSportarten());
        add(combo_sportart, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, 20));

        combo_mannschaft1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        add(combo_mannschaft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 200, 20));

        combo_mannschaft2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        add(combo_mannschaft2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 200, 20));

        lbl_sportart.setText("Sportart");
        add(lbl_sportart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btn_uebernehmen.setText("Übernehmen");
        btn_uebernehmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uebernehmenActionPerformed(evt);
            }
        });
        add(btn_uebernehmen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void button_speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_speichernActionPerformed
        // TODO add your handling code here:
        // 
        
      
        Integer tag = (Integer) comboBox_day.getSelectedItem();
        Integer monat = (Integer) comboBox_month.getSelectedItem();
        Integer jahr = (Integer) comboBox_year.getSelectedItem(); 
        String datum = tag + "." + monat + "." + jahr;
        
        Sportart spo = (Sportart) combo_sportart.getSelectedItem();
        Mannschaft m1 = (Mannschaft) combo_mannschaft1.getSelectedItem();
        Mannschaft m2 = (Mannschaft) combo_mannschaft1.getSelectedItem();
        
       
         Verwaltung.getInstance().legeSpielAn(m1,m2,spo,1,datum);
        
        
       
        
        
       
    }//GEN-LAST:event_button_speichernActionPerformed

    private void btn_uebernehmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uebernehmenActionPerformed
        combo_mannschaft1.setModel(ComboBoxModels.getMannschaften((Sportart) combo_sportart.getSelectedItem()));
        combo_mannschaft2.setModel(ComboBoxModels.getMannschaften((Sportart) combo_sportart.getSelectedItem()));
    }//GEN-LAST:event_btn_uebernehmenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_uebernehmen;
    private javax.swing.JButton button_speichern;
    private javax.swing.JComboBox comboBox_day;
    private javax.swing.JComboBox comboBox_month;
    private javax.swing.JComboBox comboBox_year;
    private javax.swing.JComboBox<String> combo_mannschaft1;
    private javax.swing.JComboBox<String> combo_mannschaft2;
    private javax.swing.JComboBox<String> combo_sportart;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_allgemeineInfos;
    private javax.swing.JLabel lbl_datum;
    private javax.swing.JLabel lbl_day;
    private javax.swing.JLabel lbl_mannschaft1;
    private javax.swing.JLabel lbl_mannschaft2;
    private javax.swing.JLabel lbl_month;
    private javax.swing.JLabel lbl_sportart;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_year;
    // End of variables declaration//GEN-END:variables
}
