/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import sportverein.Help;
import sportverein.Mannschaft;
import sportverein.Mitglied;
import sportverein.Person;
import sportverein.Sportart;
import sportverein.Sportler;
import sportverein.Verwaltung;

/**
 *
 * @author steffen
 */
public class SportartAnlegenPanel extends javax.swing.JPanel {

    /**
     * Creates new form Sportler
     */
    public SportartAnlegenPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_mannschaft1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        button_speichern = new javax.swing.JButton();
        lbl_sportart = new javax.swing.JLabel();
        txt_field_sport_name = new javax.swing.JTextField();
        lbl_min_spieler_anzahl_value = new javax.swing.JLabel();
        slider_min_anzahl_spieler = new javax.swing.JSlider();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setText("Legen sie eine Sportart an");
        add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, 404, 44));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 56, 591, -1));

        lbl_mannschaft1.setText("mindest Anzahl Spieler:");
        add(lbl_mannschaft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 591, 10));

        button_speichern.setText("Speichern");
        button_speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_speichernActionPerformed(evt);
            }
        });
        add(button_speichern, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        lbl_sportart.setText("Sportart Name");
        add(lbl_sportart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_field_sport_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_field_sport_nameActionPerformed(evt);
            }
        });
        add(txt_field_sport_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 420, -1));

        lbl_min_spieler_anzahl_value.setText("0");
        add(lbl_min_spieler_anzahl_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 20, -1));

        slider_min_anzahl_spieler.setMaximum(20);
        slider_min_anzahl_spieler.setValue(0);
        slider_min_anzahl_spieler.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_min_anzahl_spielerStateChanged(evt);
            }
        });
        add(slider_min_anzahl_spieler, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 390, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void button_speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_speichernActionPerformed
        String sportartName = txt_field_sport_name.getText();
        int minAnzahlSpieler = slider_min_anzahl_spieler.getValue(); 
         Verwaltung.getInstance().legeSportartAn(sportartName, minAnzahlSpieler);
  
    }//GEN-LAST:event_button_speichernActionPerformed

    private void txt_field_sport_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_field_sport_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_field_sport_nameActionPerformed

    private void slider_min_anzahl_spielerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_min_anzahl_spielerStateChanged
        // TODO add your handling code here:
        String s = String.valueOf(slider_min_anzahl_spieler.getValue());
        lbl_min_spieler_anzahl_value.setText(s);
    }//GEN-LAST:event_slider_min_anzahl_spielerStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_speichern;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_mannschaft1;
    private javax.swing.JLabel lbl_min_spieler_anzahl_value;
    private javax.swing.JLabel lbl_sportart;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JSlider slider_min_anzahl_spieler;
    private javax.swing.JTextField txt_field_sport_name;
    // End of variables declaration//GEN-END:variables
}
