/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import sportverein.Help;
import sportverein.Mitglied;
import sportverein.Person;
import sportverein.Sportart;
import sportverein.Sportler;
import sportverein.Verwaltung;

/**
 *
 * @author steffen
 */
public class SportlerAnlegenPanel extends javax.swing.JPanel {

    /**
     * Creates new form Sportler
     */
    public SportlerAnlegenPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_allgemeineInfos = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txtF_name = new javax.swing.JTextField();
        lbl_nachname = new javax.swing.JLabel();
        txtF_nachname = new javax.swing.JTextField();
        lbl_geschlecht = new javax.swing.JLabel();
        comboBox_geschlecht = new javax.swing.JComboBox();
        lbl_alter = new javax.swing.JLabel();
        lbl_day = new javax.swing.JLabel();
        comboBox_day = new javax.swing.JComboBox();
        lbl_month = new javax.swing.JLabel();
        comboBox_month = new javax.swing.JComboBox();
        lbl_year = new javax.swing.JLabel();
        comboBox_year = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_sporterInfo = new javax.swing.JLabel();
        lbl_sportarten = new javax.swing.JLabel();
        scrollPane_sportarten = new javax.swing.JScrollPane();
        list_sportarten = new javax.swing.JList();
        lbl_verletzt = new javax.swing.JLabel();
        checkbox_verletzt = new javax.swing.JCheckBox();
        lbl_spielstaerke = new javax.swing.JLabel();
        comboBox_spielstaerke = new javax.swing.JComboBox();
        button_speichern = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setText("Legen sie eine Sportler an");
        add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, 404, 44));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 56, 591, -1));

        lbl_allgemeineInfos.setText("Allgemeine Informationen");
        add(lbl_allgemeineInfos, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 74, -1, -1));

        lbl_name.setText("Name");
        add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 110, -1, -1));

        txtF_name.setToolTipText("geben Sie den Vorname des Sportlers ein");
        txtF_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF_nameActionPerformed(evt);
            }
        });
        add(txtF_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 469, -1));

        lbl_nachname.setText("Nachname");
        add(lbl_nachname, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 152, -1, -1));
        add(txtF_nachname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 147, 469, -1));

        lbl_geschlecht.setText("Geschlecht");
        add(lbl_geschlecht, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 195, -1, -1));

        comboBox_geschlecht.setModel(ComboBoxModels.getGeschlechter());
        comboBox_geschlecht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_geschlechtActionPerformed(evt);
            }
        });
        add(comboBox_geschlecht, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 191, -1, -1));

        lbl_alter.setText("Alter");
        add(lbl_alter, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 236, -1, -1));

        lbl_day.setText("Tag");
        add(lbl_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 236, 85, -1));

        comboBox_day.setModel(ComboBoxModels.getTage());
        add(comboBox_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        lbl_month.setText("Monat");
        add(lbl_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 236, 85, -1));

        comboBox_month.setModel((ComboBoxModels.getMonate()));
        add(comboBox_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 270, -1, -1));

        lbl_year.setText("Jahr");
        add(lbl_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 236, 110, -1));

        comboBox_year.setModel(ComboBoxModels.getJahre());
        add(comboBox_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 270, 110, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 303, 591, 10));

        lbl_sporterInfo.setText("Sportler spezifische Informationen");
        add(lbl_sporterInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 319, -1, -1));

        lbl_sportarten.setText("Sportarten");
        add(lbl_sportarten, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 353, -1, -1));

        list_sportarten.setModel(ListModels.getSportarten());
        scrollPane_sportarten.setViewportView(list_sportarten);

        add(scrollPane_sportarten, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 353, 143, 180));

        lbl_verletzt.setText("Verletzt");
        add(lbl_verletzt, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 353, -1, -1));

        checkbox_verletzt.setText("ja");
        checkbox_verletzt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_verletztActionPerformed(evt);
            }
        });
        add(checkbox_verletzt, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 353, -1, -1));

        lbl_spielstaerke.setText("Spielstärke");
        add(lbl_spielstaerke, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 394, -1, -1));

        comboBox_spielstaerke.setModel(ComboBoxModels.getSpielstaerke());
        add(comboBox_spielstaerke, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 394, -1, -1));

        button_speichern.setText("Speichern");
        button_speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_speichernActionPerformed(evt);
            }
        });
        add(button_speichern, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 551, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void button_speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_speichernActionPerformed
        // TODO add your handling code here:
        // 
        String name = txtF_name.getText();
        String nachname = txtF_nachname.getText();
        char geschlecht = 'm';
        if (comboBox_geschlecht.getSelectedIndex() == 1) {
            geschlecht = 'w';
        }
      
        Integer tag = (Integer) comboBox_day.getSelectedItem();
        Integer monat = (Integer) comboBox_month.getSelectedItem();
        Integer jahr = (Integer) comboBox_year.getSelectedItem(); 
        String geburtstag = tag + "." + monat + "." + jahr;
        
        int alter = Help.alterAusDatumString(geburtstag);
      
        double nr = Mitglied.getNaechsteNr();
        
        ArrayList<Sportart> sportarten = new ArrayList<Sportart>();
        for (Object o : list_sportarten.getSelectedValuesList()) {
            // casting object to String
            String s = (String) o;
            Sportart sportart = Verwaltung.getInstance().findSportart(s);
            if (sportart != null) {
                sportarten.add(sportart);
            } 
        }
        boolean verletzt = checkbox_verletzt.isSelected();
        int spielstaerke = (int)comboBox_spielstaerke.getSelectedItem();
       
        System.out.println(name);
        System.out.println(nachname);
        System.out.println(geschlecht);
        System.out.println(geburtstag);
        System.out.println(alter);
        System.out.println(nr);
        for (Sportart sportart : sportarten) {
            System.out.println(sportart.getName());
        }
        System.out.println(verletzt);
        System.out.println(spielstaerke);
        
        System.out.println("Aktuelle Anzahle der Mitglieder: " + Verwaltung.getInstance().getAnzahlMitglieder());
         Verwaltung.getInstance().legeSportlerAn(sportarten,verletzt,spielstaerke,nr,
                                  name,nachname,geschlecht,alter,geburtstag);
        
        
       System.out.println("Neue Anzahle der Mitglieder: " + Verwaltung.getInstance().getAnzahlMitglieder());
        
        
        System.out.println("Hier wird der Code von Karsten kommen und dann wird gespeichert");
    }//GEN-LAST:event_button_speichernActionPerformed

    private void comboBox_geschlechtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_geschlechtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_geschlechtActionPerformed

    private void checkbox_verletztActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_verletztActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkbox_verletztActionPerformed

    private void txtF_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF_nameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_speichern;
    private javax.swing.JCheckBox checkbox_verletzt;
    private javax.swing.JComboBox comboBox_day;
    private javax.swing.JComboBox comboBox_geschlecht;
    private javax.swing.JComboBox comboBox_month;
    private javax.swing.JComboBox comboBox_spielstaerke;
    private javax.swing.JComboBox comboBox_year;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_allgemeineInfos;
    private javax.swing.JLabel lbl_alter;
    private javax.swing.JLabel lbl_day;
    private javax.swing.JLabel lbl_geschlecht;
    private javax.swing.JLabel lbl_month;
    private javax.swing.JLabel lbl_nachname;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_spielstaerke;
    private javax.swing.JLabel lbl_sportarten;
    private javax.swing.JLabel lbl_sporterInfo;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_verletzt;
    private javax.swing.JLabel lbl_year;
    private javax.swing.JList list_sportarten;
    private javax.swing.JScrollPane scrollPane_sportarten;
    private javax.swing.JTextField txtF_nachname;
    private javax.swing.JTextField txtF_name;
    // End of variables declaration//GEN-END:variables
}
