/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import sportverein.Help;
import sportverein.Mitglied;
import sportverein.Person;
import sportverein.Sportart;
import sportverein.Sportler;
import sportverein.Trainer;
import sportverein.Verwaltung;
import sportverein.Vorstand;

/**
 *
 * @author steffen
 */
public class VorstandBearbeitenPanel extends javax.swing.JPanel {

    /**
     * Creates new form Sportler
     */
    public VorstandBearbeitenPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_trainer = new javax.swing.JLabel();
        scrollPane_sportarten = new javax.swing.JScrollPane();
        list_vorstand = new javax.swing.JList();
        button_bearbeiten = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_trainer.setText("Vorstand");
        add(lbl_trainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        list_vorstand.setModel(ListModels.getVorstand());
        scrollPane_sportarten.setViewportView(list_vorstand);

        add(scrollPane_sportarten, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 270));

        button_bearbeiten.setText("Bearbeiten");
        button_bearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bearbeitenActionPerformed(evt);
            }
        });
        add(button_bearbeiten, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel3.setText("Vorstandsmitglieder");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel7.setText(String.valueOf(Verwaltung.getInstance().getVorstand().size()));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void button_bearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bearbeitenActionPerformed
        // TODO add your handling code here:
        Vorstand v  = (Vorstand) list_vorstand.getSelectedValue();
        
        VorstandBearbeitenDialog dialog = new VorstandBearbeitenDialog(new javax.swing.JFrame(), true, v);        
        dialog.setVisible(true);
    }//GEN-LAST:event_button_bearbeitenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_bearbeiten;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_trainer;
    private javax.swing.JList list_vorstand;
    private javax.swing.JScrollPane scrollPane_sportarten;
    // End of variables declaration//GEN-END:variables
}
