/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui.dialoge;

import sportverein.gui.Interfaces.Updatable;
import sportverein.gui.datenAusgabe.ComboBoxModels;
import sportverein.handler.Verwaltung;
import sportverein.models.Mannschaft;
import sportverein.models.Spiel;
import sportverein.models.Sportart;

/**
 *
 * @author steffen
 */
public class SpielBearbeitenDialog extends SpeichernDialog implements Updatable{
    Spiel spiel;
    /**
     * Creates new form SpielBearbeitenDialog
     */
    public SpielBearbeitenDialog(java.awt.Frame parent, boolean modal, Spiel spiel) {
        super(parent, modal);
        this.spiel = spiel;
        initComponents();
        updateViews();
        int tag = 0;
        int monat = 0;
        int jahr = 0;
        
        
        String[] s = spiel.getDatum().split("\\.");
        
        tag = Integer.parseInt(s[0]);
        monat = Integer.parseInt(s[1]);
        jahr = Integer.parseInt(s[2]);
        comboBox_day.setSelectedItem(tag);
        comboBox_month.setSelectedItem(monat);
        comboBox_year.setSelectedItem(jahr);
        combo_mannschaft1.setSelectedItem(spiel.getHeimMannschaft().getName());
        combo_mannschaft2.setSelectedItem(spiel.getAuswaertsMannschaft().getName());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_allgemeineInfos = new javax.swing.JLabel();
        lbl_mannschaft1 = new javax.swing.JLabel();
        lbl_mannschaft2 = new javax.swing.JLabel();
        lbl_datum = new javax.swing.JLabel();
        lbl_day = new javax.swing.JLabel();
        comboBox_day = new javax.swing.JComboBox();
        lbl_month = new javax.swing.JLabel();
        comboBox_month = new javax.swing.JComboBox();
        lbl_year = new javax.swing.JLabel();
        comboBox_year = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        button_speichern = new javax.swing.JButton();
        combo_sportart = new javax.swing.JComboBox<String>();
        combo_mannschaft1 = new javax.swing.JComboBox<String>();
        combo_mannschaft2 = new javax.swing.JComboBox<String>();
        lbl_sportart = new javax.swing.JLabel();
        btn_uebernehmen = new javax.swing.JButton();
        button_abbrechen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_title.setText("Bearbeiten sie ein Spiel an");

        lbl_allgemeineInfos.setText("Allgemeine Informationen");

        lbl_mannschaft1.setText("Mannschaft 1");

        lbl_mannschaft2.setText("Mannschaft 2");

        lbl_datum.setText("Datum");

        lbl_day.setText("Tag");

        comboBox_day.setModel(ComboBoxModels.getTage());

        lbl_month.setText("Monat");

        comboBox_month.setModel((ComboBoxModels.getMonate()));

        lbl_year.setText("Jahr");

        comboBox_year.setModel(ComboBoxModels.getJahre());

        button_speichern.setText("Speichern");
        button_speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_speichernActionPerformed(evt);
            }
        });

        combo_sportart.setModel(ComboBoxModels.getSportarten());

        combo_mannschaft1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        combo_mannschaft2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        lbl_sportart.setText("Sportart");

        btn_uebernehmen.setText("Übernehmen");
        btn_uebernehmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uebernehmenActionPerformed(evt);
            }
        });

        button_abbrechen.setText("Abbrechen");
        button_abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_abbrechenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(button_abbrechen)
                .addContainerGap(371, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_uebernehmen)
                .addGap(80, 80, 80))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lbl_allgemeineInfos))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(lbl_sportart)
                            .addGap(70, 70, 70)
                            .addComponent(combo_sportart, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(lbl_mannschaft1)
                            .addGap(35, 35, 35)
                            .addComponent(combo_mannschaft1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(lbl_mannschaft2)
                            .addGap(35, 35, 35)
                            .addComponent(combo_mannschaft2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lbl_datum)
                            .addGap(80, 80, 80)
                            .addComponent(lbl_day, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(lbl_month, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(lbl_year, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(comboBox_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(comboBox_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(comboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(button_speichern)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btn_uebernehmen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(button_abbrechen))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addComponent(lbl_allgemeineInfos)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_sportart)
                        .addComponent(combo_sportart, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_mannschaft1)
                        .addComponent(combo_mannschaft1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_mannschaft2)
                        .addComponent(combo_mannschaft2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_datum)
                        .addComponent(lbl_day)
                        .addComponent(lbl_month)
                        .addComponent(lbl_year))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboBox_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBox_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)
                    .addComponent(button_speichern)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_speichernActionPerformed
        // TODO add your handling code here:
        //

        Integer tag = (Integer) comboBox_day.getSelectedItem();
        Integer monat = (Integer) comboBox_month.getSelectedItem();
        Integer jahr = (Integer) comboBox_year.getSelectedItem();
        String datum = tag + "." + monat + "." + jahr;

        Sportart spo = Verwaltung.getInstance().findSportart(combo_sportart.getSelectedItem().toString());
        Mannschaft m1 = Verwaltung.getInstance().findMannschaft(combo_mannschaft1.getSelectedItem().toString());
        Mannschaft m2 = Verwaltung.getInstance().findMannschaft(combo_mannschaft2.getSelectedItem().toString());

        spiel.setDatum(datum);
        spiel.setHeimMannschaft(m1);
        spiel.setAuswaertsMannschaft(m2);
        spiel.setSportart(spo);
        if (Verwaltung.getInstance().getSpiel().contains(spiel)){
            Verwaltung.getInstance().getSpiel().remove(spiel);
            Verwaltung.getInstance().getSpiel().add(spiel);
            save();
        }
        

    }//GEN-LAST:event_button_speichernActionPerformed

    private void btn_uebernehmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uebernehmenActionPerformed
        combo_mannschaft1.setModel(ComboBoxModels.getMannschaften((Sportart) combo_sportart.getSelectedItem()));
        combo_mannschaft2.setModel(ComboBoxModels.getMannschaften((Sportart) combo_sportart.getSelectedItem()));
    }//GEN-LAST:event_btn_uebernehmenActionPerformed

    private void button_abbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_abbrechenActionPerformed
        cancel();
    }//GEN-LAST:event_button_abbrechenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpielBearbeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpielBearbeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpielBearbeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpielBearbeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SpielBearbeitenDialog dialog = new SpielBearbeitenDialog(new javax.swing.JFrame(), true, new Spiel());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_uebernehmen;
    private javax.swing.JButton button_abbrechen;
    private javax.swing.JButton button_speichern;
    private javax.swing.JComboBox comboBox_day;
    private javax.swing.JComboBox comboBox_month;
    private javax.swing.JComboBox comboBox_year;
    private javax.swing.JComboBox<String> combo_mannschaft1;
    private javax.swing.JComboBox<String> combo_mannschaft2;
    private javax.swing.JComboBox<String> combo_sportart;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_allgemeineInfos;
    private javax.swing.JLabel lbl_datum;
    private javax.swing.JLabel lbl_day;
    private javax.swing.JLabel lbl_mannschaft1;
    private javax.swing.JLabel lbl_mannschaft2;
    private javax.swing.JLabel lbl_month;
    private javax.swing.JLabel lbl_sportart;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_year;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateViews() {
        this.combo_sportart.setModel(ComboBoxModels.getSportarten());
        this.combo_mannschaft1.setModel(ComboBoxModels.getMannschaften(Verwaltung.getInstance().findSportart(combo_sportart.getSelectedItem().toString())));
        this.combo_mannschaft2.setModel(ComboBoxModels.getMannschaften(Verwaltung.getInstance().findSportart(combo_sportart.getSelectedItem().toString())));
    }
}
