/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui.dialoge;

import sportverein.handler.Verwaltung;
import sportverein.models.Sportart;
import java.util.ArrayList;
import sportverein.*;

/**
 *
 * @author steffen
 */
public class SportartenBearbeitenDialog extends SpeichernDialog {
    Sportart sport;
    /**
     * Creates new form SportlerWerdenDialog
     */
    public SportartenBearbeitenDialog(java.awt.Frame parent, boolean modal, Sportart sport) {
        super(parent, modal);
        this.sport = sport;
        initComponents();
        txt_field_sport_name.setText(sport.getName());
        lbl_min_spieler_anzahl_value.setText(String.valueOf(sport.getMinAnzahlSpieler()));
        slider_min_anzahl_spieler.setValue(sport.getMinAnzahlSpieler());
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        lbl_nachname = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_mannschaft1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        button_speichern = new javax.swing.JButton();
        lbl_sportart = new javax.swing.JLabel();
        txt_field_sport_name = new javax.swing.JTextField();
        lbl_min_spieler_anzahl_value = new javax.swing.JLabel();
        slider_min_anzahl_spieler = new javax.swing.JSlider();
        button_abbrechen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_title.setText("Bearbeiten Sie die Sportart");

        lbl_mannschaft1.setText("mindest Anzahl Spieler:");

        button_speichern.setText("Speichern");
        button_speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_speichernActionPerformed(evt);
            }
        });

        lbl_sportart.setText("Sportart Name");

        txt_field_sport_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_field_sport_nameActionPerformed(evt);
            }
        });

        lbl_min_spieler_anzahl_value.setText("0");

        slider_min_anzahl_spieler.setMaximum(20);
        slider_min_anzahl_spieler.setValue(0);
        slider_min_anzahl_spieler.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_min_anzahl_spielerStateChanged(evt);
            }
        });

        button_abbrechen.setText("Abbrechen");
        button_abbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_abbrechenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbl_nachname))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_sportart)
                        .addGap(80, 80, 80)
                        .addComponent(txt_field_sport_name, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_mannschaft1)
                        .addGap(32, 32, 32)
                        .addComponent(lbl_min_spieler_anzahl_value, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(slider_min_anzahl_spieler, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_speichern)
                        .addGap(18, 18, 18)
                        .addComponent(button_abbrechen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_sportart)
                            .addComponent(txt_field_sport_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slider_min_anzahl_spieler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_mannschaft1)
                                    .addComponent(lbl_min_spieler_anzahl_value))))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_speichern)
                            .addComponent(button_abbrechen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lbl_nachname)
                .addGap(439, 439, 439))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_speichernActionPerformed
        String sportartName = txt_field_sport_name.getText();
        int minAnzahlSpieler = slider_min_anzahl_spieler.getValue();
        sport.setName(sportartName);
        sport.setMinAnzahlSpieler(minAnzahlSpieler);
        
        if (Verwaltung.getInstance().getSportart().contains(sport)){
            Verwaltung.getInstance().getSportart().remove(sport);
            Verwaltung.getInstance().getSportart().add(sport);
        }
        save();
    }//GEN-LAST:event_button_speichernActionPerformed

    private void txt_field_sport_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_field_sport_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_field_sport_nameActionPerformed

    private void slider_min_anzahl_spielerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_min_anzahl_spielerStateChanged
        // TODO add your handling code here:
        String s = String.valueOf(slider_min_anzahl_spieler.getValue());
        lbl_min_spieler_anzahl_value.setText(s);
    }//GEN-LAST:event_slider_min_anzahl_spielerStateChanged

    private void button_abbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_abbrechenActionPerformed
        cancel();
    }//GEN-LAST:event_button_abbrechenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SportartenBearbeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SportartenBearbeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SportartenBearbeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SportartenBearbeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SportartenBearbeitenDialog dialog = new SportartenBearbeitenDialog(new javax.swing.JFrame(), true, new Sportart());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_abbrechen;
    private javax.swing.JButton button_speichern;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_mannschaft1;
    private javax.swing.JLabel lbl_min_spieler_anzahl_value;
    private javax.swing.JLabel lbl_nachname;
    private javax.swing.JLabel lbl_sportart;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JSlider slider_min_anzahl_spieler;
    private javax.swing.JTextField txt_field_sport_name;
    // End of variables declaration//GEN-END:variables
}
