/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportverein.gui.dialoge;

import sportverein.handler.Verwaltung;
import sportverein.models.Mitglied;
import java.util.ArrayList;
import sportverein.*;

/**
 *
 * @author steffen
 */
public class VorstandWerdenDialog extends javax.swing.JDialog {
    Mitglied mitglied;
    /**
     * Creates new form SportlerWerdenDialog
     */
    public VorstandWerdenDialog(java.awt.Frame parent, boolean modal, Mitglied mitglied) {
        super(parent, modal);
        this.mitglied = mitglied;
        initComponents();
        setLocationRelativeTo(parent);
        pack();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Vorname = new javax.swing.JLabel();
        button_speichern = new javax.swing.JButton();
        lbl_VorstandInfo = new javax.swing.JLabel();
        lbl_Nachname = new javax.swing.JLabel();
        lbl_Gehalt = new javax.swing.JLabel();
        lbl_gehalt_value = new javax.swing.JLabel();
        slider_gehalt = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_Vorname.setText(this.mitglied.getName());

        button_speichern.setText("Speichern");
        button_speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_speichernActionPerformed(evt);
            }
        });

        lbl_VorstandInfo.setText("Trainer spezifische Informationen");

        lbl_Nachname.setText(this.mitglied.getNachname());

        lbl_Gehalt.setText("Gehalt");
        lbl_Gehalt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbl_GehaltPropertyChange(evt);
            }
        });

        lbl_gehalt_value.setText("0");

        slider_gehalt.setMaximum(100000);
        slider_gehalt.setValue(0);
        slider_gehalt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_gehaltStateChanged(evt);
            }
        });
        slider_gehalt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                slider_gehaltPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_VorstandInfo)
                            .addComponent(lbl_Vorname)
                            .addComponent(lbl_Nachname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Gehalt)
                        .addGap(31, 31, 31)
                        .addComponent(lbl_gehalt_value, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_speichern)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(slider_gehalt, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_Vorname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Nachname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_VorstandInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Gehalt)
                    .addComponent(lbl_gehalt_value)
                    .addComponent(slider_gehalt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(button_speichern)
                .addGap(158, 158, 158))
        );

        lbl_Nachname.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_speichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_speichernActionPerformed
        // TODO add your handling code here:
        //
        
        String name = mitglied.getName();
        String nachname = mitglied.getNachname();
        char geschlecht = mitglied.getGeschlecht();
        String geburtstag = mitglied.getGeburtstag();
        int alter = mitglied.getAlter();
        int nr = mitglied.getNr();
        double gehalt = slider_gehalt.getValue();
        

        System.out.println("Aktuelle Anzahle der Mitglieder: " + Verwaltung.getInstance().getAnzahlMitglieder());
        Verwaltung.getInstance().legeVorstandAn(gehalt, nr, name, nachname, geschlecht, alter, geburtstag);

        System.out.println("Neue Anzahle der Mitglieder: " + Verwaltung.getInstance().getAnzahlMitglieder());

        System.out.println("Hier wird der Code von Karsten kommen und dann wird gespeichert");
        
    }//GEN-LAST:event_button_speichernActionPerformed

    private void lbl_GehaltPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbl_GehaltPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_GehaltPropertyChange

    private void slider_gehaltStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_gehaltStateChanged
        // TODO add your handling code here:
        String s = String.valueOf(slider_gehalt.getValue());
        lbl_gehalt_value.setText(s);
    }//GEN-LAST:event_slider_gehaltStateChanged

    private void slider_gehaltPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_slider_gehaltPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_slider_gehaltPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VorstandWerdenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VorstandWerdenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VorstandWerdenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VorstandWerdenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VorstandWerdenDialog dialog = new VorstandWerdenDialog(new javax.swing.JFrame(), true, new Mitglied());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_speichern;
    private javax.swing.JLabel lbl_Gehalt;
    private javax.swing.JLabel lbl_Nachname;
    private javax.swing.JLabel lbl_Vorname;
    private javax.swing.JLabel lbl_VorstandInfo;
    private javax.swing.JLabel lbl_gehalt_value;
    private javax.swing.JSlider slider_gehalt;
    // End of variables declaration//GEN-END:variables
}
